/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   core.h                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: mlebard <marvin@42.fr>                     +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2021/11/09 18:24:27 by mlebard           #+#    #+#             */
/*   Updated: 2021/11/27 16:48:18 by mlebard          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef CORE_H
# define CORE_H
# include "../libft/libft.h"
# include "sig.h"

/******************************************************************************/
/*                                                                            */
/*                           Structures                                       */
/*                                                                            */
/******************************************************************************/

/*
**  t_term: main terminal structure
**
** env     -> minishell environment, works like a regular shell env
** cmdline -> command line string, fetched by readline()
** toklst  -> token linked list, generated by lexer()
** sig     -> signal returned by core functionalities
*/

typedef struct s_term
{
	char		**env;
	char		*cmdline;
	t_list		*toklst;
	t_list		*plst;
	t_sig		sig;
}	t_term;

/******************************************************************************/
/*                                                                            */
/*                          Core functionalities                              */
/*                                                                            */
/******************************************************************************/

int		lexer(char *cmdline, t_list **toklst);

/******************************************************************************/
/*                                                                            */
/*                             Core Frees                                     */
/*                                                                            */
/******************************************************************************/

void	free_everything(t_term *t);
void	free_lexer(t_term *t);

#endif
